### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by imperator-maximus** [awxkee/pngquant.swift#3]
Hello,

two things I have:
1. LICENSE file is missing
2. I opened project but I am getting in XCode following errors:

/...pngquant.swift/Sources/pngquantc/PNGImage.mm:21:33 No visible @interface for 'NSImage' declares the selector 'makeCGImage'/.../pngquant.swift/Sources/pngquantc/PNGImage.mm:25:14 Cannot initialize a variable of type 'uint8_t *' (aka 'unsigned char *') with an rvalue of type 'void 

*'/.../pngquantc/PNGImage.mm:25:14 Cannot initialize a variable of type 'uint8_t *' (aka 'unsigned char *') with an rvalue of type 'void *'

Thank you

**Comment by awxkee** [comment]
Hi,

I made the fixes

**Comment by imperator-maximus** [comment]
thank you!
